import {StyleSheet} from 'react-native';
import {AppColors} from '../../res/colors';

export const Styles = StyleSheet.create({
  searchContainer: {
    backgroundColor: 'tr',
    width: '100%',
    borderTopWidth: 0,
    borderBottomWidth: 0,
  },
  demoScreen: {
    flex: 1,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  item: {
    padding: 10,
    fontSize: 18,
    height: 44,
    color: AppColors.extras.black,
  },
  itemDark: {
    padding: 10,
    fontSize: 18,
    height: 44,
    color: AppColors.extras.white,
  },
  container: {
    ...StyleSheet.absoluteFillObject,
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    flex: 1,
    ...StyleSheet.absoluteFillObject,
  },
  mapMarkerIconSelected: {
    height: 30,
    width: 30,
  },
  mapMarkerIcon: {
    height: 25,
    width: 25,
  },
  mapIcon: {
    height: 25,
    width: 25,
    tintColor: AppColors.extras.black,
  },
  mapIconDark: {
    height: 25,
    width: 25,
    tintColor: AppColors.extras.white,
  },
  searchIcon: {
    height: 25,
    width: 25,
    tintColor: AppColors.extras.textGray,
  },
  searchIconDark: {
    height: 25,
    width: 25,
    tintColor: AppColors.extras.textSearch,
  },
  popupIcon: {
    height: 60,
    width: 60,
    borderRadius: 10,
  },
  themeChangeContainer: {
    alignItems: 'center',
    backgroundColor: AppColors.extras.white,
    borderRadius: 100,
    top: 105,
    elevation: 5,
    height: 40,
    justifyContent: 'center',
    position: 'absolute',
    right: 20,
    shadowColor: AppColors.extras.black,
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 15,
    width: 40,
  },
  themeChangeContainerDark: {
    alignItems: 'center',
    backgroundColor: AppColors.extras.darkTheme,
    borderRadius: 100,
    top: 105,
    elevation: 5,
    height: 40,
    justifyContent: 'center',
    position: 'absolute',
    right: 20,
    shadowColor: AppColors.extras.white,
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 15,
    width: 40,
  },
  searchIconView: {
    alignItems: 'center',
    height: 45,
    justifyContent: 'center',
    paddingLeft: 15,
    paddingRight: 5,
    width: 45,
  },
  popupImage: {
    alignItems: 'center',
    borderRadius: 30,
    justifyContent: 'center',
  },
  searchBar: {
    borderRadius: 5,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    height: 45,
  },

  searchText: {
    color: AppColors.extras.black,
    flex: 1,
    fontSize: 14,
  },
  searchTextDark: {
    color: AppColors.extras.white,
    flex: 1,
    fontSize: 14,
  },
  searchTextContainer: {
    flex: 1,
    height: 45,
  },
  popupTextContainer: {
    flex: 1,
    marginStart: 10,
  },
  searchBarContainerDark: {
    backgroundColor: AppColors.extras.darkTheme,
    borderRadius: 15,
    left: 10,
    position: 'absolute',
    right: 10,
    top: 40,
    elevation: 6,
    shadowColor: AppColors.extras.white,
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 15,
  },
  searchBarContainer: {
    backgroundColor: AppColors.extras.white,
    borderRadius: 15,
    left: 10,
    position: 'absolute',
    right: 10,
    top: 40,
    elevation: 6,
    shadowColor: AppColors.extras.black,
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 15,
  },
  popupContainer: {
    flex: 1,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: AppColors.extras.white,
    borderRadius: 15,
    left: 10,
    position: 'absolute',
    right: 10,
    bottom: 30,
    elevation: 6,
    shadowColor: AppColors.extras.black,
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 15,
  },
  popupContainerDark: {
    flex: 1,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: AppColors.extras.darkTheme,
    borderRadius: 15,
    left: 10,
    position: 'absolute',
    right: 10,
    bottom: 30,
    elevation: 6,
    shadowColor: AppColors.extras.white,
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 15,
  },
  popupSubHeaderText: {
    fontSize: 15,
    color: AppColors.extras.textGray,
  },
  popupSubHeaderTextDark: {
    fontSize: 15,
    color: AppColors.extras.textSearch,
  },
  popupHeaderText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: AppColors.extras.black,
  },
  popupHeaderTextDark: {
    fontSize: 18,
    fontWeight: 'bold',
    color: AppColors.extras.white,
  },
  mapMarker: {
    alignItems: 'center',
    backgroundColor: AppColors.extras.white,
    borderRadius: 100,
    borderColor: AppColors.extras.black,
    borderWidth: 0.3,
    elevation: 5,
    height: 50,
    justifyContent: 'center',
    shadowColor: AppColors.extras.black,
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 1,
    width: 50,
  },
  markerContainer: {width: 60, height: 60, backgroundColor: 'transparent'},
  mapMarkerDark: {
    alignItems: 'center',
    backgroundColor: AppColors.extras.darkTheme,
    borderRadius: 100,
    borderColor: AppColors.extras.white,
    borderWidth: 0.2,
    elevation: 5,
    height: 60,
    justifyContent: 'center',

    shadowColor: AppColors.extras.white,
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 1,
    width: 60,
  },
  mapMarkerSelected: {
    alignItems: 'center',
    backgroundColor: AppColors.extras.white,
    borderRadius: 100,
    borderColor: AppColors.extras.black,
    borderWidth: 1,
    elevation: 5,
    height: 60,
    justifyContent: 'center',

    shadowColor: AppColors.extras.black,
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 1,
    width: 60,
  },
  mapMarkerSelectedDark: {
    alignItems: 'center',
    backgroundColor: AppColors.extras.darkTheme,
    borderRadius: 100,
    borderColor: AppColors.extras.white,
    borderWidth: 1,
    elevation: 5,
    height: 60,
    justifyContent: 'center',

    shadowColor: AppColors.extras.white,
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 1,
    width: 60,
  },
  navigationIconContainer: {
    alignItems: 'center',
    backgroundColor: AppColors.extras.white,
    borderRadius: 100,
    top: 160,
    elevation: 5,
    height: 40,
    justifyContent: 'center',
    position: 'absolute',
    right: 20,
    shadowColor: AppColors.extras.black,
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 5,
    width: 40,
  },
  navigationIconContainerDark: {
    alignItems: 'center',
    backgroundColor: AppColors.extras.darkTheme,
    borderRadius: 100,
    top: 160,
    elevation: 5,
    height: 40,
    justifyContent: 'center',
    position: 'absolute',
    right: 20,
    shadowColor: AppColors.extras.white,
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 5,
    width: 40,
  },
});
export default Styles;
